### PR TITLE
Issue #29: validateVMRef: Return error when the VM does not exist

### LINKED ISSUE #29: Fix crc-driver-libvirt crash due to insufficient checks in validateVmRef
I've hit a crash in crc-driver-libvirt, but after attempting a fix, I can no longer reproduce :(
My setup was in a 'weird' state (I pressed ctrl+C at a random time during `crc start`), and `crc stop` was failing with:
```
(crc) DBG | Fetching VM...                         
(crc) Failed to fetch machine        
(crc) DBG | panic: runtime error: invalid memory address or nil pointer dereference
(crc) DBG | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x58087a]
(crc) DBG |                                                                        
(crc) DBG | goroutine 24 [running]:                                               
(crc) DBG | github.com/libvirt/libvirt-go.(*Domain).GetState(0x0, 0x0, 0x0, 0x0, 0x0)
(crc) DBG |     /root/go/pkg/mod/github.com/libvirt/libvirt-go@v3.4.0+incompatible/domain.go:1015 +0x5a
(crc) DBG | github.com/code-ready/machine-driver-libvirt.(*Driver).GetState(0xc00017c000, 0x18, 0x7f10314a9440, 0x0)
(crc) DBG |     /go/src/github.com/code-ready/machine-driver-libvirt/libvirt.go:404 +0x81              
(crc) DBG | github.com/code-ready/machine/libmachine/drivers/rpc.(*RPCServerDriver).GetState(0xc000168060, 0xebfd10, 0xc00016c5b0, 0x0, 0x0)
(crc) DBG |     /root/go/pkg/mod/github.com/code-ready/machine@v0.0.0-20190821063716-34d5b6049a38/libmachine/drivers/rpc/server_driver.go:197 +0x33
(crc) DBG | reflect.Value.call(0xc000182480, 0xc000176270, 0x13, 0x8f714b, 0x4, 0xc000057f18, 0x3, 0x3, 0xc000146000, 0x0, ...)             
(crc) DBG |     /usr/local/go/src/reflect/value.go:447 +0x454                                                                                      
(crc) DBG | reflect.Value.Call(0xc000182480, 0xc000176270, 0x13, 0xc000040f18, 0x3, 0x3, 0x0, 0x0, 0x0)                                                                                                            
(crc) DBG |     /usr/local/go/src/reflect/value.go:308 +0xa4                                                                                                                                                       
(crc) DBG | net/rpc.(*service).call(0xc00016a2c0, 0xc000178000, 0xc000018740, 0xc000018750, 0xc000171280, 0xc000168640, 0x8453c0, 0xebfd10, 0x16, 0x875520, ...)                                                   
(crc) DBG |     /usr/local/go/src/net/rpc/server.go:384 +0x14e                                                                                                                                                     
(crc) DBG | created by net/rpc.(*Server).ServeCodec                                                                                                                                                                
(crc) DBG |     /usr/local/go/src/net/rpc/server.go:481 +0x47e                                                                                                                                                     
Stopping "crc"...   
```

### PR DESCRIPTION
**Pull request by cfergeau**
The code expects that when validateVMRef is successful, domain.VM is
valid, so we have to return an error when domain.VM could not be set
because a domain with that name does not exist.

This fixes https://github.com/code-ready/machine-driver-libvirt/issues/29

### CODE REVIEW

File: libvirt.go [hunk 1]
```diff
@@ -437,6 +437,7 @@ func (d *Driver) validateVMRef() error {
 		vm, err := conn.LookupDomainByName(d.MachineName)
 		if err != nil {
 			log.Warnf("Failed to fetch machine")
+			return fmt.Errorf("Failed to fetch machine '%s'", d.MachineName)
```
Comment (praveenkumar) [inline libvirt.go:440]: :+1:

**Review by praveenkumar — APPROVED** [review]
